# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: vad.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'vad.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tvad.proto\x12\x03vad\"\x82\x01\n\nAudioChunk\x12\x12\n\naudio_data\x18\x01 \x01(\x0c\x12\x13\n\x0bsample_rate\x18\x02 \x01(\x05\x12\x10\n\x08\x63hannels\x18\x03 \x01(\x05\x12\x10\n\x08theshold\x18\x04 \x01(\x02\x12\x12\n\nframe_size\x18\x05 \x01(\x02\x12\x13\n\x0bwindow_size\x18\x06 \x01(\x02\"<\n\x14VoiceDetectionResult\x12\x10\n\x08is_voice\x18\x01 \x01(\x08\x12\x12\n\nconfidence\x18\x02 \x01(\x02\x32V\n\x15VoiceActivityDetector\x12=\n\x0b\x44\x65tectVoice\x12\x0f.vad.AudioChunk\x1a\x19.vad.VoiceDetectionResult(\x01\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'vad_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_AUDIOCHUNK']._serialized_start=19
  _globals['_AUDIOCHUNK']._serialized_end=149
  _globals['_VOICEDETECTIONRESULT']._serialized_start=151
  _globals['_VOICEDETECTIONRESULT']._serialized_end=211
  _globals['_VOICEACTIVITYDETECTOR']._serialized_start=213
  _globals['_VOICEACTIVITYDETECTOR']._serialized_end=299
# @@protoc_insertion_point(module_scope)
