[global]
type=global
user_agent=Asterisk 22

[transport-udp]
type=transport
protocol=udp
bind=0.0.0.0:5060
local_net=192.168.101.0/24
external_media_address=192.168.101.40
external_signaling_address=192.168.101.40


[1003]
type=endpoint
context=internal
disallow=all
allow=ulaw,alaw,slin16
aors=1003
direct_media=no
rtp_symmetric=yes
force_rport=yes
rewrite_contact=yes
media_address=192.168.101.40

[1003]
type=aor
max_contacts=1
remove_existing=yes


; --- 1000 ---
[1000]
type=endpoint
context=internal
disallow=all
allow=ulaw,alaw,slin16
auth=1000-auth
aors=1000
direct_media=no
rtp_symmetric=yes
force_rport=yes
rewrite_contact=yes
media_address=192.168.101.40

[1000-auth]
type=auth
auth_type=userpass
username=1000
password=1000

[1000]
type=aor
max_contacts=1
remove_existing=yes


; --- 1001 ---
[1001]
type=endpoint
context=internal
disallow=all
allow=ulaw,alaw,slin16
auth=1001-auth
aors=1001
direct_media=no
rtp_symmetric=yes
force_rport=yes
rewrite_contact=yes
media_address=192.168.101.40

[1001-auth]
type=auth
auth_type=userpass
username=1001
password=1001

[1001]
type=aor
max_contacts=1
remove_existing=yes

; --- 1002 ---
[1002]
type=endpoint
context=internal
disallow=all
allow=ulaw,alaw,slin16
auth=1002-auth
aors=1002
direct_media=no
rtp_symmetric=yes
force_rport=yes
rewrite_contact=yes
media_address=192.168.101.40

[1002-auth]
type=auth
auth_type=userpass
username=1002
password=1002

[1002]
type=aor
max_contacts=1
remove_existing=yes


; --- 1004 ---
[1004]
type=endpoint
context=internal
disallow=all
allow=ulaw,alaw,slin16
auth=1004-auth
aors=1004
direct_media=no
rtp_symmetric=yes
force_rport=yes
rewrite_contact=yes
media_address=192.168.101.40

[1004-auth]
type=auth
auth_type=userpass
username=1004
password=1004

[1004]
type=aor
max_contacts=1
remove_existing=yes


; --- 1005 ---
[1005]
type=endpoint
context=internal
disallow=all
allow=ulaw,alaw,slin16
auth=1005-auth
aors=1005
direct_media=no
rtp_symmetric=yes
force_rport=yes
rewrite_contact=yes
media_address=192.168.101.40

[1005-auth]
type=auth
auth_type=userpass
username=1005
password=1005

[1005]
type=aor
max_contacts=1
remove_existing=yes


; --- 1006 ---
[1006]
type=endpoint
context=internal
disallow=all
allow=ulaw,alaw,slin16
auth=1006-auth
aors=1006
direct_media=no
rtp_symmetric=yes
force_rport=yes
rewrite_contact=yes
media_address=192.168.101.40

[1006-auth]
type=auth
auth_type=userpass
username=1006
password=1006

[1006]
type=aor
max_contacts=1
remove_existing=yes


; --- 1007 ---
[1007]
type=endpoint
context=internal
disallow=all
allow=ulaw,alaw,slin16
auth=1007-auth
aors=1007
direct_media=no
rtp_symmetric=yes
force_rport=yes
rewrite_contact=yes
media_address=192.168.101.40

[1007-auth]
type=auth
auth_type=userpass
username=1007
password=1007

[1007]
type=aor
max_contacts=1
remove_existing=yes


; --- 1008 ---
[1008]
type=endpoint
context=internal
disallow=all
allow=ulaw,alaw,slin16
auth=1008-auth
aors=1008
direct_media=no
rtp_symmetric=yes
force_rport=yes
rewrite_contact=yes
media_address=192.168.101.40

[1008-auth]
type=auth
auth_type=userpass
username=1008
password=1008

[1008]
type=aor
max_contacts=1
remove_existing=yes


; --- 1009 ---
[1009]
type=endpoint
context=internal
disallow=all
allow=ulaw,alaw,slin16
auth=1009-auth
aors=1009
direct_media=no
rtp_symmetric=yes
force_rport=yes
rewrite_contact=yes
media_address=192.168.101.40

[1009-auth]
type=auth
auth_type=userpass
username=1009
password=1009

[1009]
type=aor
max_contacts=1
remove_existing=yes
