[from-trunk]
exten => 555202044,1,Progress()
 same => n,Set(SESSION_ID=${PJSIP_HEADER(read,X-Live-Session-ID)})
 same => n,Set(RPI=${PJSIP_HEADER(read,Remote-Party-ID)})
 same => n,Set(CALLER_NUM=${FILTER(0-9,${CUT(RPI,@,1)})})
 same => n,Set(UUID=${SHELL(uuidgen | tr -d '\n')})
 same => n,MixMonitor(${CALLER_NUM}-${SESSION_ID}.wav)
 same => n,NoOp(Session ID: ${SESSION_ID} | UUID: ${UUID} | Caller: ${CALLER_NUM})
 same => n,Set(CDR(session_id)=${SESSION_ID})
 same => n,Playtones(ring)
 same => n,Wait(3)
 same => n,StopPlaytones()
 same => n,Answer()
 same => n,Playback(intro_8k)
 same => n,Stasis(ai-callcenter, incoming)
 same => n,Hangup()