[transport-udp]
type=transport
protocol=udp
bind=0.0.0.0

; ===== SIP TRUNK (IP AUTH) =====
[mytrunk]
type=endpoint
transport=transport-udp
context=from-trunk
disallow=all
allow=g722,ulaw,alaw,slin16
direct_media=no
rtp_symmetric=yes
force_rport=yes
rewrite_contact=yes
aors=mytrunk_aor
callerid=998555202044 <998555202044>



[mytrunk_aor]
type=aor
;contact=sip:172.25.250.45
contact=sip:172.28.120.26

[mytrunk_identify]
type=identify
endpoint=mytrunk
;match=172.25.250.45
match=172.28.120.26